### ISSUE TITLE
Error parsing FASTA in multiple passes

### ISSUE THREAD

**Issue by sbliven** [biojava/biojava#659]
Dak reported the following bug on the mailing list:

> I have a FASTA file that contain one sequence. I initialized FASTA reader as described in the tutorial, called process() and get one record as expected. However, if I re-initialized another FASTA reader opening the same one-record file, called process(1) and null is returned. If I tried to read two-record FASTA file, the first process(1) works, but not the second call to process(1) return null. Based on a superficial glance, it looks like the if statement at line 194 of FastaReader.java may be the culprit.

@andreasprlic created a branch, https://github.com/biojava/biojava/tree/DakFastaHeader which contains the failing TestFASTAReader.

**Comment by psoares** [comment]
Looks like a bug introduced a long time ago by #282

**Comment by arojnuckarin** [comment]
Created pull request #687

**Comment by lafita** [comment]
Was this completely fixed by #687?

**Comment by arojnuckarin** [comment]
I recently pulled biojava-core 4.2.9 from maven repo and it looks like this particular bug is still there.
I was thinking that the since the pull request has been merged, the fix should propagate into maven sooner or later, but it looks like that's not the case. 

Is there something that need to take place before the change can go into the 4.2.x official release? Anything that I need to do?

Thanks,
dak

**Comment by josemduarte** [comment]
The pull request went into the `master` branch only and not into the `bugfixes-4.2` branch. The fix is already in the 5.0.0-alpha13 release and it will be there also when the final 5.0.0 goes out.

If you want the fix in the next 4.2.x release, you will need to make a separate pull request for that. You will just need to cherry-pick the appropriate commits. Thanks!

**Comment by arojnuckarin** [comment]
Do we have an estimate as to when 5.0.0 will go out and how much work is likely involved in upgrading from the code that uses 4.2.x to 5.0?

Thanks again for your help,
dak

**Comment by josemduarte** [comment]
The intention is to release 5.0.0 early next year. Most changes are in the structure module, adapting code that uses the structure module can require some work. For other modules the changes are much less dramatic.

**Comment by josemduarte** [comment]
@arojnuckarin I've just cherry-picked your fix into the bugfixes-4.2 branch. I'm going to release a new bugfix version in the next days.

**Comment by josemduarte** [comment]
Reading the above, it looks that this is fixed. Closing. If you know otherwise please reopen.
